logging:
  file:
    name: ${user.dir}/log/boot_study.log    # 로깅 파일 위치이다.
    max-history: 7                    # 로그 파일 삭제 주기이다. 7일 이후 로그는 삭제한다.
    max-size: 10MB                    # 로그 파일 하나당 최대 파일 사이즈이다.
  level:                              # 각 package 별로 로깅 레벨을 지정할 수 있다.
    com.example : debug
    com.mybatis : debug
  #  com.example.springbootstudy.study2 : info

rabbitmq:
  image: rabbitmq:management
  ports:
    - "5672:5672"
    - "15672:15672"

spring:
  datasource:
    url: jdbc:h2:file:~/data/h2/testdb;MODE=MySQL
    platform: h2
    username: sa
    password:
    driverClassName: org.h2.Driver

# H2 Settings
h2:
  console:
    enabled: true
    path: /h2-console


mybatis:
  type-aliases-package: com.example.myproject.mapper
  mapper-locations: /mappers/**/*.xml